# Numpy Array

array當中只能放單一種型態，

In [1]:
import numpy as np

---
### 建立
---

In [2]:
np.array([1,2,3,4,5])   #直接建立

array([1, 2, 3, 4, 5])

In [3]:
list1=[1,2,3,4,5]       #由list建立
np.array(list1)

array([1, 2, 3, 4, 5])

In [4]:
list1=[1.1,2,3.2,4,5]   #會自動轉換成float
np.array(list1)

array([1.1, 2. , 3.2, 4. , 5. ])

可以明確指定資料型態

In [5]:
list1=[1,2,3,4,5] 
np.array(list1, dtype='float32')
#基本的標準型態有
  #bool_
  #int_、int8、int16、int32、int64
  #float_、float16、float32、float64

array([1., 2., 3., 4., 5.], dtype=float32)

In [6]:
type(np.array(list1))  #array所建立的型態為  numpy.ndarray

numpy.ndarray

---
### 快速創建
---

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.full((2,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [11]:
print(np.arange(0,10))
print(np.arange(0,10,2))  #(start,end, interval)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [12]:
np.empty((2,3))   #填充無異議數值

array([[ 1.01582801e+094, -2.69941271e-260, -9.70701200e+303],
       [ 1.84790850e+216,  2.60802184e-310,  0.00000000e+000]])

區間

In [13]:
np.linspace(0,1,5)    #(start, end, divide)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

random系列

In [14]:
np.random.random((3,3))   # 0~1 亂數取值

array([[0.87942619, 0.02963913, 0.23103751],
       [0.1607016 , 0.5406201 , 0.18733547],
       [0.06111391, 0.45307642, 0.80705951]])

In [15]:
np.random.normal(0,1,(3,3))   # (mean, std , dim) 亂數取值

array([[ 0.8682696 ,  0.84605437,  0.64433221],
       [ 1.79247223,  1.10643462,  0.66473541],
       [ 1.15235814, -0.32997275, -0.17976258]])

In [16]:
np.random.randint(0,10,(3,3))    # (start, end, dim) 亂數取值

array([[4, 3, 8],
       [1, 4, 6],
       [1, 2, 6]])

from系列

In [17]:
#numpy.fromfunction

In [18]:
#numpy.fromfile

---
### 基本屬性
---
ndarray.ndim：NumPy ndarray物件的維度<br>
ndarry.shape：ndarry物件的每一個維度的大小(size)，回傳資料類別為Tuple<br>
ndarry.size：ndarry物件所組成之array的總元素數量，回應之數值會等於ndarray.shape的每個元素相乘<br>
ndarry.dtype：ndarray物件內組成元素的型態<br>
ndarray.itemsize：陣列中每一個元素的大小(Bytes) (ex: int16=>16/8=2 Bytes)<br>
ndarry.data：這是一個存有實際陣列元素的緩衝，通常我們不需要使用這個屬性，因為我們可以使用index存取這些元素。

In [19]:
testArray = np.random.random((3,3))

In [20]:
testArray

array([[0.47257224, 0.58014861, 0.82737502],
       [0.20244762, 0.91122099, 0.30045863],
       [0.35277312, 0.23494724, 0.50719577]])

In [21]:
# ndarray.ndim
print("ndim:{}".format(testArray.ndim))
# ndarry.shape
print("shape:{}".format(testArray.shape))
# ndarry.size
print("size:{}".format(testArray.size))
# ndarry.dtype
print("dtype:{}".format(testArray.dtype))
# ndarray.itemsize
print("itemsize:{}".format(testArray.itemsize))
# ndarry.data
print("data:{}".format(testArray.data))

ndim:2
shape:(3, 3)
size:9
dtype:float64
itemsize:8
data:<memory at 0x0000021E1D143708>


---
### 基本操作
---

In [22]:
a = np.array([20,30,40,50])
b = np.arange(4)

### <li>加減乘除、邏輯判斷

In [23]:
a,   b,   a-b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]), array([20, 29, 38, 47]))

In [24]:
a/10,   b/1,  a>b 

(array([2., 3., 4., 5.]),
 array([0., 1., 2., 3.]),
 array([ True,  True,  True,  True]))

In [25]:
a = np.array([[1,2],[2,4]])
b = np.array([[1,1],[2,2]])

In [26]:
print('a+b =',a+b,'\n')       #上下相加  
print('a*b =',a*b,'\n')       #上下相乘  
print('a@b =',a@b,'\n')       #矩陣相乘
print('a.dot(b) =',a.dot(b),'\n')  #矩陣相乘

a+b = [[2 3]
 [4 6]] 

a*b = [[1 2]
 [4 8]] 

a@b = [[ 5  5]
 [10 10]] 

a.dot(b) = [[ 5  5]
 [10 10]] 



### <li>陣列索引、切片

In [27]:
a2 = np.array([[1,2,3,4],[2,4,6,8]])

In [28]:
a2[0]

array([1, 2, 3, 4])

In [29]:
a2[0][2]

3

In [30]:
a2[0,2]    #[][]可以,合併

3

In [31]:
a2[0:2]

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [32]:
a2[0,0:4]

array([1, 2, 3, 4])

In [33]:
a2[0,0:4:2]

array([1, 3])

In [34]:
a2[0,::]   #若有沒有設定者，預設為 start=0, stop=size, step=1

array([1, 2, 3, 4])

In [35]:
a2[0,::-1]  #step=-1 可以反轉

array([4, 3, 2, 1])

In [36]:
a2[::,::] 

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [37]:
a3 = np.array([[1,2,3,4],[2,4,6,8],[3,6,9,12]])
a3

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [38]:
a3[:2,:3]    #[ x維 , y維 ]

array([[1, 2, 3],
       [2, 4, 6]])

In [39]:
a3[:,::2]    #[ x維 , y維 ]

array([[1, 3],
       [2, 6],
       [3, 9]])

In [40]:
a3[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  6,  4,  2],
       [12,  9,  6,  3]])

In [41]:
a3[:,1],    a3[1,:]

(array([2, 4, 6]), array([2, 4, 6, 8]))

### <li>子陣列之結果為view，需要用copy才能成為獨立副本

In [42]:
b3 = a3.copy()
b3

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [43]:
b2 = b3[:2,]
b2

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [44]:
b2[0] = b2[0]*2
b2

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [45]:
b3

array([[ 2,  4,  6,  8],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [46]:
a3

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

### <li>重新塑形

In [47]:
grid = np.arange(0,10)
print('grid=',grid)
print('shape=',grid.shape)

grid= [0 1 2 3 4 5 6 7 8 9]
shape= (10,)


In [48]:
grid_re = grid.reshape((2,5))
grid_re

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
grid_re[1][1]=0
grid

array([0, 1, 2, 3, 4, 5, 0, 7, 8, 9])

In [50]:
grid = np.arange(1,10)
grid.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [51]:
grid = np.arange(1,10)
grid[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

### <li>串接

In [52]:
a = np.array([1,2,3,4])
b = np.array([1,1,2,2])
concat = np.concatenate([a,b])
concat

array([1, 2, 3, 4, 1, 1, 2, 2])

In [53]:
a = np.array([[1,2,3,4],[2,4,6,8]])
b = np.array([[1,1,2,2],[2,2,1,1]])
concat = np.concatenate([a,b])
print(concat)
print("type=",type(concat))
print('ndim =',concat.ndim)
print('shape =',concat.shape)

[[1 2 3 4]
 [2 4 6 8]
 [1 1 2 2]
 [2 2 1 1]]
type= <class 'numpy.ndarray'>
ndim = 2
shape = (4, 4)


In [54]:
a = np.array([[1,2,3,4],[2,4,6,8]])
b = np.array([[1,1,2,2],[2,2,1,1]])
concat = np.concatenate([a,b],axis=0)
print(concat)
print("type=",type(concat))
print('ndim =',concat.ndim)
print('shape =',concat.shape)

[[1 2 3 4]
 [2 4 6 8]
 [1 1 2 2]
 [2 2 1 1]]
type= <class 'numpy.ndarray'>
ndim = 2
shape = (4, 4)


In [55]:
a = np.array([[1,2,3,4],[2,4,6,8]])
b = np.array([[1,1,2,2],[2,2,1,1]])
concat = np.concatenate([a,b],axis=1)
print(concat)
print("type=",type(concat))
print('ndim =',concat.ndim)
print('shape =',concat.shape)

[[1 2 3 4 1 1 2 2]
 [2 4 6 8 2 2 1 1]]
type= <class 'numpy.ndarray'>
ndim = 2
shape = (2, 8)


In [56]:
a = np.array([[1,2,3,4],[2,4,6,8]])
b = np.array([1,1,2,2])
concat = np.vstack([a,b])    #垂直堆疊
print(concat)
print("type=",type(concat))
print('ndim =',concat.ndim)
print('shape =',concat.shape)

[[1 2 3 4]
 [2 4 6 8]
 [1 1 2 2]]
type= <class 'numpy.ndarray'>
ndim = 2
shape = (3, 4)


In [57]:
a = np.array([[1,2,3,4],[2,4,6,8]])
y = np.array([[99],[99]])
concat = np.hstack([a,y])   #水平疊加
print(concat)
print("type=",type(concat))
print('ndim =',concat.ndim)
print('shape =',concat.shape)

[[ 1  2  3  4 99]
 [ 2  4  6  8 99]]
type= <class 'numpy.ndarray'>
ndim = 2
shape = (2, 5)


In [58]:
a = np.array([[1,2,3,4],[2,4,6,8]])
b = np.array([[1,1,2,2],[2,2,1,1]])
concat = np.dstack([a,b])
print(concat)
print("type=",type(concat))
print('ndim =',concat.ndim)
print('shape =',concat.shape)

[[[1 1]
  [2 1]
  [3 2]
  [4 2]]

 [[2 2]
  [4 2]
  [6 1]
  [8 1]]]
type= <class 'numpy.ndarray'>
ndim = 3
shape = (2, 4, 2)


In [59]:
a = np.array([[1,2,3,4],[2,4,6,8]])
b = np.array([[1,1,2,2],[2,2,1,1]])
c = np.array([[5,5,6,6],[7,7,8,8]])
concat = np.stack([a,b,c])      #預設為 x 軸(axis=0)
print(concat)
print("type=",type(concat))
print('ndim =',concat.ndim)
print('shape =',concat.shape)

[[[1 2 3 4]
  [2 4 6 8]]

 [[1 1 2 2]
  [2 2 1 1]]

 [[5 5 6 6]
  [7 7 8 8]]]
type= <class 'numpy.ndarray'>
ndim = 3
shape = (3, 2, 4)


In [60]:
a = np.array([[1,2,3,4],[2,4,6,8]])
b = np.array([[1,1,2,2],[2,2,1,1]])
c = np.array([[5,5,6,6],[7,7,8,8]])
concat = np.stack([a,b,c],axis=0)         # X =>  Y  => Z    (3,2,4)
print(concat)
print("type=",type(concat))
print('ndim =',concat.ndim)
print('shape =',concat.shape)

[[[1 2 3 4]
  [2 4 6 8]]

 [[1 1 2 2]
  [2 2 1 1]]

 [[5 5 6 6]
  [7 7 8 8]]]
type= <class 'numpy.ndarray'>
ndim = 3
shape = (3, 2, 4)


In [61]:
a = np.array([[1,2,3,4],[2,4,6,8]])
b = np.array([[1,1,2,2],[2,2,1,1]])
c = np.array([[5,5,6,6],[7,7,8,8]])
concat = np.stack([a,b,c],axis=1)         # Y =>  X  => Z    (2,3,4)
print(concat)
print("type=",type(concat))
print('ndim =',concat.ndim)
print('shape =',concat.shape)

[[[1 2 3 4]
  [1 1 2 2]
  [5 5 6 6]]

 [[2 4 6 8]
  [2 2 1 1]
  [7 7 8 8]]]
type= <class 'numpy.ndarray'>
ndim = 3
shape = (2, 3, 4)


In [62]:
a = np.array([[1,2,3,4],[2,4,6,8]])
b = np.array([[1,1,2,2],[2,2,1,1]])
c = np.array([[5,5,6,6],[7,7,8,8]])
concat = np.stack([a,b,c],axis=2)         # Y =>  Z  => X    (2,4,3)    #重心放在新維上
print(concat)
print("type=",type(concat))
print('ndim =',concat.ndim)
print('shape =',concat.shape)

[[[1 1 5]
  [2 1 5]
  [3 2 6]
  [4 2 6]]

 [[2 2 7]
  [4 2 7]
  [6 1 8]
  [8 1 8]]]
type= <class 'numpy.ndarray'>
ndim = 3
shape = (2, 4, 3)


### <li>分割
    割完會變list !!

In [63]:
a = np.array([1, 2, 3, 4, 1, 1, 2, 2])
print(np.split(a,[0]))
print(np.split(a,[1]))
print(np.split(a,[1,2]))
print(np.split(a,[1,2]))

[array([], dtype=int32), array([1, 2, 3, 4, 1, 1, 2, 2])]
[array([1]), array([2, 3, 4, 1, 1, 2, 2])]
[array([1]), array([2]), array([3, 4, 1, 1, 2, 2])]
[array([1]), array([2]), array([3, 4, 1, 1, 2, 2])]


In [64]:
a = np.array([[1,2,3,4],[2,4,6,8],[5,5,6,6]])
print(np.vsplit(a,[2]))
print('type = ',type(np.vsplit(a,[2])))
print('len = ',len(np.vsplit(a,[2])))

print(np.vsplit(a,[1,2]))
print('type = ',type(np.vsplit(a,[1,2])))
print('len = ',len(np.vsplit(a,[1,2])))

[array([[1, 2, 3, 4],
       [2, 4, 6, 8]]), array([[5, 5, 6, 6]])]
type =  <class 'list'>
len =  2
[array([[1, 2, 3, 4]]), array([[2, 4, 6, 8]]), array([[5, 5, 6, 6]])]
type =  <class 'list'>
len =  3


In [65]:
a = np.array([[1,2,3,4],[2,4,6,8],[5,5,6,6]])
print(np.hsplit(a,[2]))
print('type = ',type(np.hsplit(a,[2])))
print('len = ',len(np.hsplit(a,[2])))

print(np.hsplit(a,[1,2]))
print('type = ',type(np.hsplit(a,[1,2])))
print('len = ',len(np.hsplit(a,[1,2])))


[array([[1, 2],
       [2, 4],
       [5, 5]]), array([[3, 4],
       [6, 8],
       [6, 6]])]
type =  <class 'list'>
len =  2
[array([[1],
       [2],
       [5]]), array([[2],
       [4],
       [5]]), array([[3, 4],
       [6, 8],
       [6, 6]])]
type =  <class 'list'>
len =  3


In [66]:
a =  np.arange(12.0).reshape (2,2,3)
a

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

In [67]:
print(np.dsplit(a,1))
print(np.dsplit(a,3))

[array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])]
[array([[[0.],
        [3.]],

       [[6.],
        [9.]]]), array([[[ 1.],
        [ 4.]],

       [[ 7.],
        [10.]]]), array([[[ 2.],
        [ 5.]],

       [[ 8.],
        [11.]]])]
