# Array的運算

In [1]:
import numpy as np

## Ufuncs
---
np.add　　　　　　　+<br> 
np.subtract　　　　　-<br>
np.negative　　　　　-<br>
np.multply　　　　　　*　<br>
np.divide　　　　　　/<br>
np.floor_divide　　　　//<br>
np.mod&nbsp　　　　%<br>
np.power　　　　　　**

In [2]:
a=np.arange(1,11).reshape((2,5))
b=np.arange(1,11)[::-1].reshape((2,5))
print(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [3]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**2)

[[11 11 11 11 11]
 [11 11 11 11 11]]
[[-9 -7 -5 -3 -1]
 [ 1  3  5  7  9]]
[[10 18 24 28 30]
 [30 28 24 18 10]]
[[ 0.1         0.22222222  0.375       0.57142857  0.83333333]
 [ 1.2         1.75        2.66666667  4.5        10.        ]]
[[ 0  0  0  0  0]
 [ 1  1  2  4 10]]
[[1 2 3 4 5]
 [1 3 2 1 0]]
[[  1   4   9  16  25]
 [ 36  49  64  81 100]]


絕對值
abs

In [4]:
a=np.arange(-5,5)
a

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [5]:
np.abs(a),np.absolute(a)

(array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4]), array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4]))

#### <li>三角函數
np.sin(x)<br>
np.cos(x)<br>
np.tan(x)<br>
np.arcsin(x)<br>
np.arccos(x)<br>
np.arctan(x)<br>

In [6]:
theta = np.linspace(0, np.pi, 3)
np.sin(theta), np.cos(theta), np.tan(theta)

(array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16]),
 array([ 1.000000e+00,  6.123234e-17, -1.000000e+00]),
 array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16]))

In [7]:
x=[-1,0,-1]
np.arcsin(x), np.arccos(x), np.arctan(x)

(array([-1.57079633,  0.        , -1.57079633]),
 array([3.14159265, 1.57079633, 3.14159265]),
 array([-0.78539816,  0.        , -0.78539816]))

#### <li>指對數
np.exp(x)　　　　　　e^x<br>
np.exp2(x)　　　　　　2^x<br>
np.power(底,指)　　　底^指<br>
np.log(x)　　　　　　ln(x)<br>
np.log2(x)　　　　　　log2(x)<br>
np.log10(x)　　　　　log10(x)<br>

In [8]:
x=[1,2,4,10]
print("x         = ",x)
print()
print("e^x       = ",np.exp(x))
print("2^x       = ",np.exp2(x))
print("3^x       = ",np.power(3,x))
print()
print("ln(x)     = ",np.log(x))
print("log2(x)   = ",np.log2(x))
print("log10(x)  = ",np.log10(x))


x         =  [1, 2, 4, 10]

e^x       =  [2.71828183e+00 7.38905610e+00 5.45981500e+01 2.20264658e+04]
2^x       =  [   2.    4.   16. 1024.]
3^x       =  [    3     9    81 59049]

ln(x)     =  [0.         0.69314718 1.38629436 2.30258509]
log2(x)   =  [0.         1.         2.         3.32192809]
log10(x)  =  [0.         0.30103    0.60205999 1.        ]


#### <li>設定輸出參數  (out= )

In [9]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
y

array([ 0., 10., 20., 30., 40.])

In [10]:
y = np.full(10,5)
y1 = np.power(y,2,out=y)
y1

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [11]:
y = np.zeros(10)
np.power(x,2,out=y[::2])
y

array([ 0.,  0.,  1.,  0.,  4.,  0.,  9.,  0., 16.,  0.])

#### <li>添加型聚合 function (.reduce(x)、.accumulate(x))

In [12]:
y = np.full(5,5)
np.add.reduce(y)

25

In [13]:
y = np.full(5,5)
np.multiply.reduce(y)

3125

In [14]:
y = np.full(5,5)
np.add.accumulate(y)

array([ 5, 10, 15, 20, 25], dtype=int32)

In [15]:
y = np.full(5,5)
np.multiply.accumulate(y)

array([   5,   25,  125,  625, 3125], dtype=int32)

In [16]:
#at、reduceat 見 Fancy

### 聚合 function
np.sum　　np.nan...<br>
np.prod　　np.nan...<br>
np.mean　　np.nan...<br>
np.std　　np.nan...<br>
np.var　　np.nan...<br>
np.min　　np.nan...<br>
np.max　　np.nan...<br>
np.argmix　　np.nan...<br>
np.argmax　　np.nan...<br>
np.mediam　　np.nan...<br>
np.perentile　　np.nan...<br>
np.any　　<br>
np.all　　


In [17]:
M = np.arange(1,7).reshape((2,3))
print(M)
print(np.sum(M))
print(np.prod(M))
print(np.mean(M))
print(np.min(M))
print(np.max(M))

[[1 2 3]
 [4 5 6]]
21
720
3.5
1
6


In [18]:
M = np.arange(0,7)
print(M)
print(np.argmin(M))  #回傳索引位置
print(np.argmax(M))  #回傳索引位置
print(np.median(M))

[0 1 2 3 4 5 6]
0
6
3.0


In [19]:
M = np.random.normal(0,1,(3,3))
print(np.std(M))
print(np.var(M))

0.849967818942935
0.72244529323861


In [20]:
M = np.arange(0,7)
print(np.percentile(M,0))
print(np.percentile(M,25))
print(np.percentile(M,50))
print(np.percentile(M,75))
print(np.percentile(M,100))    #(array , %)

0.0
1.5
3.0
4.5
6.0


In [21]:
M = np.arange(0,6).reshape((2,3))
np.any(M),np.all(M)   #判斷True

(True, False)

#### <li>添加據維度參數 axis=

In [22]:
M = np.arange(0,6).reshape((2,3))
print(M)
np.any(M,axis=0),np.all(M,axis=0),np.any(M,axis=1),np.all(M,axis=1)   #判斷True

[[0 1 2]
 [3 4 5]]


(array([ True,  True,  True]),
 array([False,  True,  True]),
 array([ True,  True]),
 array([False,  True]))

---
### Broadcasting
---
(不成size的自動簡易運算寫法)

In [23]:
a = np.arange(3)
a

array([0, 1, 2])

In [24]:
a+1

array([1, 2, 3])

In [25]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
a+b  #[0, 1, 2]會自動被拉長成 [[0, 1, 2],[0, 1, 2],[0, 1, 2]]  #1.墊維度 2.複製以拉長維度

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [27]:
b+a  #[0, 1, 2]會自動被拉長成 [[0, 1, 2],[0, 1, 2],[0, 1, 2]]  #1.墊維度 2.複製以拉長維度

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [28]:
a = np.arange(3).reshape((3,1))
b = np.arange(3)
a,b

(array([[0],
        [1],
        [2]]), array([0, 1, 2]))

In [29]:
#雙邊  Broadcasting

In [30]:
print(np.shape(a))
print(np.shape(b))

(3, 1)
(3,)


In [31]:
#(3,1) (3,)    [[0][1][2]]   [0,1,2]
#(3,1) (1,3)   [[0][1][2]]   [[0,1,2]]
#(3,3) (1,3)   [[0,0,0][1,1,1][2,2,2]]   [[0,1,2]]
#(3,3) (3,3)   [[0,0,0][1,1,1][2,2,2]]   [[0,1,2],[0,1,2],[0,1,2]]

In [32]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [33]:
# Broadcasting實用範例 

In [34]:
rand_X = np.random.random((10,3))
rand_X

array([[0.27811572, 0.78209183, 0.07620296],
       [0.17935063, 0.61828858, 0.28385916],
       [0.43665058, 0.27462323, 0.52809911],
       [0.84840234, 0.68338346, 0.27243022],
       [0.68475971, 0.66841663, 0.17730389],
       [0.67951879, 0.92445756, 0.46748724],
       [0.57188071, 0.6035705 , 0.89030591],
       [0.13256243, 0.70584651, 0.41916348],
       [0.37987509, 0.93671085, 0.88670351],
       [0.04568738, 0.1556201 , 0.75758671]])

In [35]:
min_X = np.min(rand_X)
min_X

0.04568737511255683

In [36]:
creat_X = rand_X-min_X
creat_X

array([[0.23242835, 0.73640445, 0.03051558],
       [0.13366325, 0.57260121, 0.23817178],
       [0.3909632 , 0.22893586, 0.48241174],
       [0.80271496, 0.63769608, 0.22674284],
       [0.63907233, 0.62272926, 0.13161651],
       [0.63383141, 0.87877019, 0.42179986],
       [0.52619333, 0.55788312, 0.84461853],
       [0.08687506, 0.66015914, 0.37347611],
       [0.33418772, 0.89102348, 0.84101614],
       [0.        , 0.10993273, 0.71189934]])

---
### Booling mask
---


In [37]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a[a%2!=0]

array([1, 3, 5, 7, 9])

In [39]:
a[a%2!=0]=11
a

array([ 0, 11,  2, 11,  4, 11,  6, 11,  8, 11])

In [40]:
a1 = np.full((2,2),10)
a2 = np.full((2,2),5)
a3 = np.full((2,2),1)
c = np.hstack([a1,a2,a3])
c

array([[10, 10,  5,  5,  1,  1],
       [10, 10,  5,  5,  1,  1]])

In [41]:
c>1

array([[ True,  True,  True,  True, False, False],
       [ True,  True,  True,  True, False, False]])

可搭配<br>
np.bitwise_and() = &<br>
np.bitwise_or() = |<br>
np.bitwise_xor() = ^<br>
np.bitwise_not() = ~

In [42]:
(c>1) & (c<10)

array([[False, False,  True,  True, False, False],
       [False, False,  True,  True, False, False]])

In [43]:
c[(c>1) & (c<10)]  #回傳為 1維 array

array([5, 5, 5, 5])

In [44]:
np.all(c>5,axis=1)

array([False, False])

In [45]:
np.any(c>5,axis=1)

array([ True,  True])

西雅圖雨量實例

In [46]:
import numpy as np
import pandas as pd
import requests
import io

In [47]:
url = 'https://raw.githubusercontent.com/jakevdp/PythonDataScienceHandbook/master/notebooks/data/Seattle2014.csv'
response = requests.get(url)
if response.status_code != 200:
    print('Failed to get data:', response.status_code)
else:
    print(response.content)

b'STATION,STATION_NAME,DATE,PRCP,SNWD,SNOW,TMAX,TMIN,AWND,WDF2,WDF5,WSF2,WSF5,WT01,WT05,WT02,WT03\nGHCND:USW00024233,SEATTLE TACOMA INTERNATIONAL AIRPORT WA US,20140101,0,0,0,72,33,12,340,310,36,40,-9999,-9999,-9999,-9999\nGHCND:USW00024233,SEATTLE TACOMA INTERNATIONAL AIRPORT WA US,20140102,41,0,0,106,61,32,190,200,94,116,-9999,-9999,-9999,-9999\nGHCND:USW00024233,SEATTLE TACOMA INTERNATIONAL AIRPORT WA US,20140103,15,0,0,89,28,26,30,50,63,72,1,-9999,-9999,-9999\nGHCND:USW00024233,SEATTLE TACOMA INTERNATIONAL AIRPORT WA US,20140104,0,0,0,78,6,27,40,40,45,58,1,-9999,-9999,-9999\nGHCND:USW00024233,SEATTLE TACOMA INTERNATIONAL AIRPORT WA US,20140105,0,0,0,83,-5,37,10,10,67,76,-9999,-9999,-9999,-9999\nGHCND:USW00024233,SEATTLE TACOMA INTERNATIONAL AIRPORT WA US,20140106,3,0,0,78,-5,26,210,210,112,125,1,-9999,-9999,-9999\nGHCND:USW00024233,SEATTLE TACOMA INTERNATIONAL AIRPORT WA US,20140107,122,0,0,83,50,16,160,150,45,54,-9999,-9999,-9999,-9999\nGHCND:USW00024233,SEATTLE TACOMA INTERNATION

In [48]:
type(response.content) #網頁檔案仍是bytes

bytes

In [49]:
rainfall = pd.read_csv(io.StringIO(response.content.decode('utf-8')))['PRCP']
rainfall.shape

(365,)

In [50]:
inches = rainfall/254    #1/10mm = 1 inches
inches.shape

(365,)

In [51]:
print('沒下雨天數 = ',np.sum(inches == 0))
print('下雨天數 = ',np.sum(inches != 0))
print('雨量超過0.5 inches的天數 = ',np.sum(inches > 0.5))
print('雨量小於0.1 inches的天數 = ',np.sum((inches > 0)&(inches <0.1)))

沒下雨天數 =  215
下雨天數 =  150
雨量超過0.5 inches的天數 =  37
雨量小於0.1 inches的天數 =  46


In [52]:
rainy = (inches>0)  #降雨遮罩
rainy

0      False
1       True
2       True
3      False
4      False
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21      True
22     False
23     False
24     False
25     False
26     False
27      True
28      True
29     False
       ...  
335    False
336    False
337     True
338     True
339     True
340    False
341     True
342     True
343     True
344     True
345    False
346    False
347    False
348    False
349    False
350     True
351     True
352     True
353     True
354    False
355    False
356     True
357     True
358    False
359    False
360     True
361     True
362    False
363    False
364    False
Name: PRCP, Length: 365, dtype: bool

In [53]:
summer = (np.arange(365)-172<90) & (np.arange(365)-172>0)  #建立夏天遮罩
summer

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [54]:
rainy&summer  #合起來就是夏天又下雨的遮罩喔

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...  
335    False
336    False
337    False
338    False
339    False
340    False
341    False
342    False
343    False
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352    False
353    False
354    False
355    False
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364    False
Name: PRCP, Length: 365, dtype: bool

In [55]:
print('下雨的中位數 = ',np.median(inches[rainy]))
print('最大雨量 = ',np.max(inches[rainy]))
print('夏天下雨的中位數 = ',np.median(inches[rainy&summer]))
print('夏天最大雨量 = ',np.max(inches[rainy&summer]))

下雨的中位數 =  0.19488188976377951
最大雨量 =  1.8385826771653544
夏天下雨的中位數 =  0.0610236220472441
夏天最大雨量 =  0.8503937007874016


---
### Fancy 索引
---

In [57]:
x = np.arange(10)
[x[2],x[5],x[6]]

[2, 5, 6]

In [58]:
x = np.arange(10)
ind = [2,5,6]  #可接受1D List，最好使用array
x[ind],x[[2,5,6]]

(array([2, 5, 6]), array([2, 5, 6]))

In [59]:
ind2 = np.array([[2,5,6],[1,3,5]])
x[ind2]

array([[2, 5, 6],
       [1, 3, 5]])

In [60]:
x2 = np.arange(12).reshape((3,4))
row = np.array([0,1,2])
col = np.array([1,2,3])
print(x2)
x2[row,col]     #可支援多維度指定

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 1,  6, 11])

In [61]:
x2[1,[2,0,1]]

array([6, 4, 5])

In [62]:
x2[1:,[2,0,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [63]:
mask = np.array([1,0,1,0],dtype=bool)
x2[:,mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

疊加結果(強制更新變數)

In [64]:
x = np.zeros(10)
i = [1,2,2,4,5,5,7,8,8]
x[i] += 1
x

array([0., 1., 1., 0., 1., 1., 0., 1., 1., 0.])

In [65]:
x = np.zeros(10)
i = [1,2,2,4,5,5,7,8,8]
np.add.at(x,i,1)
x

array([0., 1., 2., 0., 1., 2., 0., 1., 2., 0.])

裝箱範例

In [66]:
np.random.seed(42)
x = np.random.randn(100)
#手動計算直方圖
bins = np.linspace(-5,5,20)  #-5~5 分成20塊
counts = np.zeros_like(bins)
x,bins,counts

(array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
        -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
        -0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783,
        -0.56228753, -1.01283112,  0.31424733, -0.90802408, -1.4123037 ,
         1.46564877, -0.2257763 ,  0.0675282 , -1.42474819, -0.54438272,
         0.11092259, -1.15099358,  0.37569802, -0.60063869, -0.29169375,
        -0.60170661,  1.85227818, -0.01349722, -1.05771093,  0.82254491,
        -1.22084365,  0.2088636 , -1.95967012, -1.32818605,  0.19686124,
         0.73846658,  0.17136828, -0.11564828, -0.3011037 , -1.47852199,
        -0.71984421, -0.46063877,  1.05712223,  0.34361829, -1.76304016,
         0.32408397, -0.38508228, -0.676922  ,  0.61167629,  1.03099952,
         0.93128012, -0.83921752, -0.30921238,  0.33126343,  0.97554513,
        -0.47917424, -0.18565898, -1.10633497, -1.19620662,  0.81252582,
         1.35624003, -0.07201012,  1.0035329 ,  0.3

In [67]:
i= np.searchsorted(bins,x)  # 將 x 與bins的區塊做比對   b-1 =< x < b
i

array([11, 10, 11, 13, 10, 10, 13, 11,  9, 11,  9,  9, 10,  6,  7,  9,  8,
       11,  8,  7, 13, 10, 10,  7,  9, 10,  8, 11,  9,  9,  9, 14, 10,  8,
       12,  8, 10,  6,  7, 10, 11, 10, 10,  9,  7,  9,  9, 12, 11,  7, 11,
        9,  9, 11, 12, 12,  8,  9, 11, 12,  9, 10,  8,  8, 12, 13, 10, 12,
       11,  9, 11, 13, 10, 13,  5, 12, 10,  9, 10,  6, 10, 11, 13,  9,  8,
        9, 12, 11,  9, 11, 10, 12,  9,  9,  9,  7, 11, 10, 10, 10],
      dtype=int64)

In [68]:
np.add.at(counts,i,1)
counts

array([ 0.,  0.,  0.,  0.,  0.,  1.,  3.,  7.,  9., 23., 22., 17., 10.,
        7.,  1.,  0.,  0.,  0.,  0.,  0.])

### 排序
會建立出獨立副本

In [69]:
x = np.array([1,4,6,3,6,2,5,8])
x1 = np.sort(x)
x[0]=99
x1,x

(array([1, 2, 3, 4, 5, 6, 6, 8]), array([99,  4,  6,  3,  6,  2,  5,  8]))

In [70]:
x = np.array([1,4,6,3,6,2,5,8])
np.sort(x),x

(array([1, 2, 3, 4, 5, 6, 6, 8]), array([1, 4, 6, 3, 6, 2, 5, 8]))

In [71]:
x = np.array([1,4,6,3,6,2,5,8])
x.sort()  #直接更新進去
x

array([1, 2, 3, 4, 5, 6, 6, 8])

In [72]:
x = np.array([1,4,6,3,6,2,5,8])
argsortMask = np.argsort(x)
argsortMask,x[argsortMask]

(array([0, 5, 3, 1, 6, 2, 4, 7], dtype=int64), array([1, 2, 3, 4, 5, 6, 6, 8]))

In [73]:
rand=np.random.RandomState(42)
x=rand.randint(0,10,(4,6))
x

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [74]:
np.sort(x,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [75]:
np.sort(x,axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

區分部分大小

In [76]:
x = np.arange(0,10)[::-1]
np.partition(x,4)  #將最小的 4個 元素亂數放在前面，其餘元素亂數放後面

array([2, 1, 0, 3, 4, 5, 8, 6, 7, 9])

In [77]:
# 結構化資料